import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/Navbar";
import { Toaster } from "sonner";
import Footer from "./_components/footer/page";
import Wrapper from "./_components/wrapper";
import TanStackProvider from "@/providers/TanStackProvider";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.className} `}
      >
        <TanStackProvider>

        <Wrapper>
          <Navbar></Navbar>
        
          {children}
          </Wrapper>
          <Toaster/>
          <Footer></Footer>
        </TanStackProvider>
      </body>
    </html>
  );
}
